import tkinter
from tkinter import *
import tkinter.messagebox as msg
class BMS():
    def __init__(self,root):
        self.root=root
        self.root.geometry("500x200")
        self.root.title("BOOK MANAGEMENT SYSTEM")
        self.root.config(bg= "darkblue")
        title=Label(self.root,text="Book Management System",bg="darkblue",font=('bold','20'),fg="red")
        title.pack()
        login_button=Button(self.root,text="Login",padx=30,pady=15,bg="lightblue",font=('bold','12'),command=self.login)
        login_button.place(x=20,y=80)
        new_user_button=Button(self.root,text="New User",padx=30,pady=15,bg="lightblue",font=('bold','12'),command=self.register)
        new_user_button.place(x=160,y=80)
        available_book_button=Button(self.root,text="Available Book",padx=30,pady=15,bg="lightblue",font=('bold','12'),command=self.login)
        available_book_button.place(x=330,y=80)
    def login(self):
        login_window=Tk()
        login_window.title("Login Page")
        login_window.geometry("500x300")
        login_window.config(bg="darkblue")
        login_username=Label(login_window,text="Username",bg="darkblue",font=('bold','20'),fg="white")
        login_username.place(x=30,y=50)
        login_password=Label(login_window,text="Password",bg="darkblue",font=('bold','20'),fg="white")
        login_password.place(x=30,y=130)
        self.loginusername_entry=Entry(login_window)
        self.loginusername_entry.place(x=200,y=60)
        self.loginpassword_entry=Entry(login_window)
        self.loginpassword_entry.place(x=200,y=140)
        login_submit_button=Button(login_window,text="Login Now",bg="lightblue",font=('bold','12'),command=self.request_submit)
        login_submit_button.place(x=160,y=190)
        new_user_button=Button(login_window,text="New User",bg="lightblue",padx=10,font=('bold','12'),command=self.register)
        new_user_button.place(x=400,y=190)

    def register(self):
        register_window=Tk()
        register_window.title("Student Registeration")
        register_window.geometry("500x400")
        register_window.config(bg="darkblue")
        register_name=Label(register_window,text="Student Details",bg="darkblue",font=('bold','20'),fg="red")
        register_name.pack()
        register_name=Label(register_window,text="Name",bg="darkblue",font=('bold','20'),fg="white")
        register_name.place(x=90,y=50)
        self.name_entry=Entry(register_window)
        self.name_entry.place(x=260,y=60)
        register_address=Label(register_window,text="Address",bg="darkblue",font=('bold','20'),fg="white")
        register_address.place(x=90,y=100)
        self.address_entry=Entry(register_window)
        self.address_entry.place(x=260,y=110)
        register_gender=Label(register_window,text="Gender (M/F)",bg="darkblue",font=('bold','20'),fg="white")
        register_gender.place(x=90,y=150)
        self.gender_entry=Entry(register_window)
        self.gender_entry.place(x=260,y=160)
        register_mobile_no=Label(register_window,text="Mobile No",bg="darkblue",font=('bold','20'),fg="white")
        register_mobile_no.place(x=90,y=200)
        self.no_entry=Entry(register_window)
        self.no_entry.place(x=260,y=210)
        register_email=Label(register_window,text="Email ID",bg="darkblue",font=('bold','20'),fg="white")
        register_email.place(x=90,y=250)
        self.email_entry=Entry(register_window)
        self.email_entry.place(x=260,y=260)
        register_password=Label(register_window,text="Password",bg="darkblue",fg="white",font=('bold','20'))
        register_password.place(x=90,y=300)
        self.password_entry=Entry(register_window)
        self.password_entry.place(x=260,y=310)
        register_submit_button=Button(register_window,text="SUBMIT",bg="lightblue",font=('bold','12'),command=self.add_student)
        register_submit_button.place(x=190,y=350)
    def request_submit(self):
        request_window=Tk()
        request_window.geometry("500x200")
        request_window.title("Book Management System")
        request_window.config(bg="darkblue")
        request_button=Button(request_window,text="Request Book",bg="lightblue",font=('bold','20'),command=self.request_book)
        request_button.place(x=30,y=50)
        submit_button=Button(request_window,text="Submit Book",bg="lightblue",font=('bold','20'),command=self.submit_book)
        submit_button.place(x=250,y=50)
    def request_book(self):
        rwindow=Tk()
        rwindow.geometry("500x400")
        rwindow.title("Request Book")
        rwindow.config(bg="darkblue")
        register_name=Label(rwindow,text="Author",bg="darkblue",font=('bold','20'),fg="white")
        register_name.place(x=90,y=50)
        self.name_en=Entry(rwindow)
        self.name_en.place(x=260,y=60)
        book_name_request=Label(rwindow,text="Book Name",bg="darkblue",font=('bold','20'),fg="white")
        book_name_request.place(x=90,y=100)
        self.book_name_entry=Entry(rwindow)
        self.book_name_entry.place(x=260,y=110)
        order_book=Button(rwindow,text="ORDER",bg="darkblue",fg="white",font=('bold','20'))
        order_book.place(x=200,y=250)
    def submit_book(self):
        swindow=Tk()
        swindow.geometry("500x300")
        swindow.title("Submit Book")
        swindow.config(bg="darkblue")
        s_author=Label(swindow,text="Author",bg="darkblue",font=('bold','20'),fg="white")
        s_author.place(x=60,y=50)
        self.author_entry=Entry(swindow)
        self.author_entry.place(x=260,y=60)
        book_name=Label(swindow,text="Book Name",bg="darkblue",font=('bold','20'),fg="white")
        book_name.place(x=60,y=100)
        self.book_entry=Entry(swindow)
        self.book_entry.place(x=260,y=110)
        s_price=Label(swindow,text="Price",bg="darkblue",font=('bold','20'),fg="white")
        s_price.place(x=60,y=150)
        self.price_entry=Entry(swindow)
        self.price_entry.place(x=260,y=150)
        s_submit=Button(swindow,text="Submit",bg="lightblue",font=('bold','14'),command=self.add_book)
        s_submit.place(x=190,y=200)
    def add_book(self):
        import mysql.connector
        mydb=mysql.connector.connect(host='localhost',port='3306',username='root',password='yuvi@1234',database='library_management')
        mycursor=mydb.cursor()
        author=self.author_entry.get()
        book=self.book_entry.get()
        price=self.price_entry.get()
        mycursor.execute("insert into book values(%s,%s,%s)",(author,book,price))
        mydb.commit()
        msg.showinfo("Book","Book added to stock")
    def add_student(self):
        import mysql.connector
        mydb=mysql.connector.connect(host='localhost',port='3306',username='root',password='yuvi@1234',database='library_management')
        mycursor=mydb.cursor()
        name=self.name_entry.get()
        address=self.address_entry.get()
        gender=self.gender_entry.get()
        phone=self.no_entry.get()
        email=self.email_entry.get()
        password=self.password_entry.get()
        mycursor.execute("insert into student values(%s,%s,%s,%s,%s,%s)",(name,address,gender,phone,email,password))
        mydb.commit()
        msg.showinfo("student database","new student added")
    # def student_login(self):
    #     import mysql.connector
    #     mydb=mysql.connector.connect(host='localhost',port='3306',username='root',password='yuvi@1234',database='library_management')
    #     mycursor=mydb.cursor()
    #     name=self.loginusername_entry.get()
    #     password=self.loginpassword_entry.get()

root=Tk()
obj=BMS(root)
root.mainloop()